name: CMake

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  release:
    types: [prereleased]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.2
        arch: x64

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.0
        arch: win64_msvc2019_64
        aqtversion: ==1.2.2

    - name: Install Vulkan SDK
      if: matrix.platform != 'macos-latest'
      uses: humbletim/setup-vulkan-sdk@v1.0.2

    - name: Build and Install
      run: |
        mkdir build; cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=installed \
          -DALL_PLUGINS=ON \
          -GNinja
        cmake --build .
        cmake --install .

    - name: Generate 7zip
      run: 7z a Plugins.7z -- build/installed/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: QvPlugin-${{ runner.os }}.7z
        path: Plugins.7z

    - name: Upload to GitHub Release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'release'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Plugins.7z
        asset_name: QvPlugin-${{ runner.os }}.7z
        tag: ${{ github.ref }}
        overwrite: true
